### PR TITLE
[NO MERGE] Prepare mvn central

### PR DESCRIPTION
**Pull request by bgiori**
This PR modifies the gradle build files for hosting on the maven central repository. The gradle file (`gradle/gradle-mvn-push.gradle`) which is used to upload the archives to maven central is taken from https://github.com/JakeWharton/timber
    
The group details for the project are located in the root build.properties file. This file contains, among others:
 * Version: 0.6.3-SNAPSHOT
 * Group: io.runtime.mcumgr
    
The package specific artifact ID and name are located in the module gradle.properties file. This file contains:
 * Artifact ID: mcumgr-android
 * Name: McuManager Android
 * Package Type: aar

I have uploaded an initial SNAPSHOT archive to the sonatype snapshots repo here: https://oss.sonatype.org/content/repositories/snapshots/io/runtime/mcumgr/mcumgr-android/0.6.3-SNAPSHOT/

This snapshot can be tested by adding the snapshot repo to gradle repositories for all projects:

```
allprojects {
    repositories {
        // ...
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
}
```

### CODE REVIEW

**Comment by bgiori** [comment]
56867b5 Commit message:
```
Brief notes:
 * Rename module mcumgr-android-lib -> mcumgr-core.
    - Artifact renamed from mcumgr-android -> mcumgr-core.
 * Breakout ble package from core into mcumgr-ble.
    - mcumgr-ble is built as separate artifact which includes core as an
      api dependency.

This change is useful to allow users to reimplement their own transport
layer or potentially add a new transport all together. Furthermore,
since I plan on adding the CoAP BLE transport at some point to the main
repo, this allows me to simply add a new module, mcumgr-coap-ble, rather
than adding it to mcumgr-android and forceing users to add dependencies
which they will not use.

Finally, I can forsee a future where the core could be broken out into
it's own plain java library for use in non-android applications. This
would simplify that process as it is already built as a separate
artifact.
```

**Comment by bgiori** [comment]
Yes, I just confirmed that the annotations work with kotlin. The android support annotations were replaced with jetbrains in order to remove the android support annotations dependency. Once Timber releases 5.0.0 with plain old java support, the core can be made into a plain old java library too.

Would be worth doing another pass on the library to make sure everything that can be annotated is.

**Comment by twyatt** [comment]
> Does it works well with Kotlin? The `@NonNull` and `@Nullable` are converted to required or optional variables there, if project accessed with Kotlin.

@philips77
- **Without** the nullability annotations then Kotlin sees variables/parameters as platform types (meaning Kotlin can't enforce the nullability but in the calling Kotlin code we can explicitly specify the nullability)
- **With** the nullability annotations then the nullness of variables/parameters are strictly enforced. To avoid the [billion dollar mistake](https://en.wikipedia.org/wiki/Tony_Hoare#Apologies_and_retractions), marking with `@NonNull` or `@Nullable` is strongly preferred.

**Comment by twyatt** [comment]
> The android support annotations were replaced with jetbrains

Sounds good, Kotlin supports a [bunch of nullability annotations](https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations) (JetBrain's are included in the list).

**Comment by philips77** [comment]
If you are taking the transport out of the library, should the McuMgrScheme be replaced with building the message (headers) by a transport layer? Now it limits transports to BLE, COAP_BLE, COAP_UDP.

**Comment by bgiori** [comment]
I'm going to merge this PR first thing tomorrow if no one objects.

**Pull request merged**
